// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prnauaeqflapasesrnen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBybmF1YWVxZmxhcGFzZXNybmVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNDQwOTYsImV4cCI6MjA2ODkyMDA5Nn0.STLxYWXMMtXnPiVmG8JBBh0J1i00f5T6Ol1ZUldDphM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});